import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:the_weather/domain/weather/condition/condition.dart';
import 'package:the_weather/domain/weather/hour/value_objects.dart';

part 'hour.freezed.dart';

@freezed
class Hour with _$Hour {
  const factory Hour({
    Time_epoch? time_epoch,
    Time? time,
    Temp_c? temp_c,
    Temp_f? temp_f,
    Is_day? is_day,
    Condition? condition,
    Wind_mph? wind_mph,
    Wind_kph? wind_kph,
    Wind_degree? wind_degree,
    Wind_dir? wind_dir,
    Pressure_mb? pressure_mb,
    Pressure_in? pressure_in,
    Precip_mm? precip_mm,
    Precip_in? precip_in,
    Humidity? humidity,
    Cloud? cloud,
    Feelslike_c? feelslike_c,
    Feelslike_f? feelslike_f,
    Windchill_c? windchill_c,
    Windchill_f? windchill_f,
    Heatindex_c? heatindex_c,
    Heatindex_f? heatindex_f,
    Dewpoint_c? dewpoint_c,
    Dewpoint_f? dewpoint_f,
    Will_it_rain? will_it_rain,
    Chance_of_rain? chance_of_rain,
    Will_it_snow? will_it_snow,
    Chance_of_snow? chance_of_snow,
    Vis_km? vis_km,
    Vis_miles? vis_miles,
    Gust_mph? gust_mph,
    Gust_kph? gust_kph,
    Uv? uv,
  }) = _Hour;

  factory Hour.empty() => Hour(
        time_epoch: Time_epoch(0),
        time: Time(''),
        temp_c: Temp_c(0.0),
        temp_f: Temp_f(0.0),
        is_day: Is_day(0),
        condition: Condition.empty(),
        wind_mph: Wind_mph(0.0),
        wind_kph: Wind_kph(0.0),
        wind_degree: Wind_degree(0),
        wind_dir: Wind_dir(''),
        pressure_mb: Pressure_mb(0.0),
        pressure_in: Pressure_in(0.0),
        precip_mm: Precip_mm(0.0),
        precip_in: Precip_in(0.0),
        humidity: Humidity(0),
        cloud: Cloud(0),
        feelslike_c: Feelslike_c(0.0),
        feelslike_f: Feelslike_f(0.0),
        windchill_c: Windchill_c(0.0),
        windchill_f: Windchill_f(0.0),
        heatindex_c: Heatindex_c(0.0),
        heatindex_f: Heatindex_f(0.0),
        dewpoint_c: Dewpoint_c(0.0),
        dewpoint_f: Dewpoint_f(0.0),
        will_it_rain: Will_it_rain(0),
        chance_of_rain: Chance_of_rain(0),
        will_it_snow: Will_it_snow(0),
        chance_of_snow: Chance_of_snow(0),
        vis_km: Vis_km(0.0),
        vis_miles: Vis_miles(0.0),
        gust_mph: Gust_mph(0.0),
        gust_kph: Gust_kph(0.0),
        uv: Uv(0.0),
      );
}
